### PR TITLE
Update SDL2 version

### PR DESCRIPTION
**Pull request by luizdepra**
This PR updates the SDL2 submodule to fix the build problem reported at #1769.

### CODE REVIEW

**Comment by nesbox** [comment]
Unfortunately, the Android build fails with this update
https://github.com/nesbox/TIC-80/actions/runs/1768620530
image

I'll try to fix it later, thanks.

**Comment by luizdepra** [comment]
I can try fixing it too. No problem.

Another thing, I think it would be great if the all CI builds runs and reports show here in the PR. So, we contributors could see if there is any problem with our contributed code.

I didn't look at the CI pipeline yet, but I can help you with that if you want.

**Comment by nesbox** [comment]
> I can try fixing it too. No problem.

Great, please, if not difficult :)
As far as I understand, we need to update `build/android` from the `vendor/sdl2/android-project` folder.

> I think it would be great if the all CI builds runs and reports show here in the PR

I just enabled Actions for PRs in the project settings.
Thanks.

**Comment by luizdepra** [comment]
So, @nesbox. I add `pull_request` into GH Action to test the build on my fork. Tell me if you want to remove it.

Well, the build is still failing, but I got some progress. I updated the using the `sdl2/android-project` files, but removed the JNI related things. I noticed that `libhdiapi` as removed from the example code, and many lines of java code were modified too. Could check if everything is fine on this?

But, there is a new error because Gradle was updated too.

```
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```
If I understood right, we need to update the Java version on `nesbox/android-tic80`. I think only you could make a new release of this container image.

**Comment by luizdepra** [comment]
Maybe I got everything wrong. I think the real problem is that `libhdiapi` is missing. I'm going to try the android build on my machine to see if is it the realm issue.

**Comment by nesbox** [comment]
I also think that we need to update the Java version on `nesbox/android-tic80` (I'll try later), but as a temporary solution, we could try to keep Gradle in the same version.

**Comment by luizdepra** [comment]
I tried not updating Gradle and got the same error. [See here](https://github.com/luizdepra/TIC-80/runs/5022958145?check_suite_focus=true#step:4:6870).

I don't know whether the Android Build should ship or not with `hidapi`. I know that the linking step of `lib/libtic80.so` is failing, so maybe we should add or remove something related to `hidapi` from CMake rules.

**Comment by nesbox** [comment]
> maybe we should add or remove something related to hidapi from CMake rules.

Seems yes, pls remove the `CMakeLists.txt:984` `target_link_libraries(tic80 hidapi)` line.

**Comment by luizdepra** [comment]
Yeah! It is fixed!

First, sorry for the noise in this PR. Also sorry for my editor removing lots of trailing whitespaces and reformatting a `.yml` file causing more changes. I can revert it back if you want, but IMHO formatting and triming spaces are not a bad thing.

It wasn't need to update the `build/android` folder at all. The relevant changes are in the `CMakeLists.txt` file, at lines [474](https://github.com/nesbox/TIC-80/pull/1825/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR474) and [985](https://github.com/nesbox/TIC-80/pull/1825/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR985). Basically, I removed `hidapi` from the linking step and forced SDL2 to be compiled with `-fPIC` for Android.

**Comment by nesbox** [comment]
Great, build is fixed, but unfortunately, the app doesn't start :(
Seems, we have to update all the Java files too.

**Comment by luizdepra** [comment]
Done!

Is there a way I could download the generated artifacts from the CI build to test it?

**Comment by nesbox** [comment]
> Is there a way I could download the generated artifacts from the CI build to test it?

Sure, please go to Actions https://github.com/nesbox/TIC-80/actions, select your commit and you will find the artifacts at the bottom of the page.
https://github.com/nesbox/TIC-80/actions/runs/1784048184

Thank you for the help.

**Comment by luizdepra** [comment]
I think it is fixed now. The Android build launched and ran without errors on my phone.

The app was still trying to load `hidapi`, so I removed the entry inside `getLibraries` from `TIC.java`.

**Review by nesbox — APPROVED** [review]
Awesome, thank you for the help.

**Pull request merged**
