### PR TITLE
S7 Scheme language support

### PR DESCRIPTION
**Pull request by sthilaid**
These changes add scheme support to tic-80

### CODE REVIEW

**Comment by nesbox** [comment]
Please make all the builds passed https://github.com/nesbox/TIC-80/actions/runs/4074721024
image

**Comment by sthilaid** [comment]
@nesbox I'm having a hard time with the rpi-baremetal and n3ds platforms with those jmp issues. I need to distinguish those platforms so that I can get them to use the other set of jmps definitions but I don't know how to. Is there any macros that you know that would distinguish them?

Thanks!

**Comment by sthilaid** [comment]
and... nope! but maybe those need to be included from somewhere... I'll look more in details tonight. At least, IO should be officially disabled now :)

**Comment by sthilaid** [comment]
okay, I need more help. I managed to make all the targets compile, but there remains this link issue on baremetalpi that I have no clue why it's happening. It seems that the (now renamed) libs7scheme.a lib doesn't get linked properly with libtic80core for some reason... :( Can anyone help me?

**Comment by sogaiu** [comment]
@sthilaid Not sure, but is it possible something for s7 needs to be added around [here](https://github.com/sthilaid/TIC-80/blob/main/build/baremetalpi/Makefile#L33-L34)?

**Comment by sthilaid** [comment]
@sogaiu omg, you're a genius! hehe I didn't know that the baremetal target had it's own makefile...

**Comment by sthilaid** [comment]
image

**Comment by sthilaid** [comment]
i'm noticing that Janel and Scheme would probably be need to be added to the export-stub actions once they make it fully into the version.

**Comment by nesbox** [comment]
Yes, pls add `scheme` to export stubs here https://github.com/nesbox/TIC-80/blob/b62be5f570c10f1fa21570b418d2bf3e4d061dfc/.github/workflows/build.yml#L688

**Comment by sthilaid** [comment]
I don't know why this would fail, I simply added scheme to the workflow list. Was there more to do? I don't know much about github workflows...

**Comment by sthilaid** [comment]
ok i think we're good to go!

**Comment by nesbox** [comment]
Everything looks good now and I'm going to merge it, one thing could you please make `vendor/s7` folder as a submodule to your repo, perhaps as separate pull request.
Thank you for the help.

BTW, pls don't forget add yourself to the Credits page https://github.com/nesbox/TIC-80#credits

**Review by nesbox — APPROVED** [review]

**Comment by sthilaid** [comment]
I wanted to use s7 as a submodule, but I wasn't able to clone their git repo (it's hosted in the Standford university gitlabs https://cm-gitlab.stanford.edu/bil/s7). I also had to edit it to disable io and make it compile on some targets, so we're not on sync with them. I will try to get my changes merged up and see if they can make their repo more accessible.

I would love to continue contributing to tic80, I'm having a ton of fun. I have a few questions about that:
- Is there a good place where all the tic80 contributors to chat about changes? I'm discussing in the tic80 general chat but it seems this should be more a place for users to talk about stuff...
- I'm working on code editor changes to add support for "structured editing" of lisp-like language. I'll send a pull request soon, but I also want to make an emacs-like mode to the editor. I've put the option to toggle it on in the code theme config, but I feel it's a bit obscure... Is there a better place for that?

Thanks!

**Comment by nesbox** [comment]
> Is there a good place where all the tic80 contributors to chat about changes?

Usually, we discuss changes directly in the Issues.

> I've put the option to toggle it on in the code theme config, but I feel it's a bit obscure... Is there a better place for that?

You already put the option to theme config and main menu in your PR :) there is no better place for it

**Pull request merged**
