### PR TITLE
order langauges by alphabetical order

### PR DESCRIPTION
**Pull request by joshgoebel**
If we aren't playing favorites anymore then this order really should be alphabetical, not historic.

### CODE REVIEW

**Review by nesbox — APPROVED** [review]

**Comment by remi6397** [comment]
This made fennel the default language. :grin::v:

**Comment by joshgoebel** [comment]
Default in what sense? New does not have a default anymore.

**Comment by remi6397** [comment]
Not the language, I mean the demo that's loaded by default, it used to be the Lua hello. Maybe we should randomize it? :smile:

**Comment by joshgoebel** [comment]
Oops, that was unintentional.  @nesbox Should we go back and hard-wire Lua as the starter language when the app first opens?

**Comment by nesbox** [comment]
> Should we go back and hard-wire Lua as the starter language when the app first opens?

of course, Lua has to be the first, also I need to be more careful when reviewing PRs

**Comment by nesbox** [comment]
reverted here 7364cbbad4cfee4897a5deb8ae00700fad51d0f0

**Comment by joshgoebel** [comment]
Could we have just have fixed the default issue without reverting the ordering?

**Comment by nesbox** [comment]
Please make new PR with the fixed ordering and Lua by default, I don't see other variants.
Sorry for the confusion.

**Pull request merged**
