### PR TITLE
Upgrade Python language bindings to `v1.2.x`

### PR DESCRIPTION
**Pull request by blueloveTH**
## Description

TIC-80's Python implementation, [pocketpy](https://github.com/blueloveTH/pocketpy) `v1.0.0` was a bit outdated.

I am upgrading the interpreter into the latest version `v1.2.x`. When this pr is completed, I will remove `(WIP)`.

## Related Issues
- [x] #2296 
- [x] #2297 
- [x] #2150
- [x] #2316 
- [x] #2317 

## New Features Up to `v1.2.x`

| Feature                                     | Description                                                  | Version |
| ------------------------------------------- | ------------------------------------------------------------ | ------- |
| **(TIC-80's current)**                       | -                                           | 1.0.0   |
| cascading assignment                        | `a=b=1`                                                      | 1.0.3   |
| cascading comparasion                       | `a<b<c`                                                      | 1.0.3   |
| keyword arguments                           | `def f(**kwargs): pass`                                      | 1.0.3   |
| unpacking builder for `list/tuple/dict/set` | `[*a, *b, 1, 2]`                                             | 1.0.3   |
| `traceback` module                          | `msg: str = traceback.format_exc()`                          | 1.0.3   |
| 1-element tuple                             | `(1,)`                                                       | 1.0.4   |
| `pickle` module                             | see [pickle module](https://pocketpy.dev/modules/pickle/)    | 1.0.4   |
| `long` type for arbitrary sized integers    | see [long type](https://pocketpy.dev/features/long/)         | 1.0.4   |
| reversed operators                          | `__radd__`, `__rsub__`, `__rmul__`                           | 1.0.4   |
| cmake build support                         | see [CMakeLists.txt](https://github.com/blueloveTH/pocketpy/blob/main/CMakeLists.txt) | 1.0.9   |
| `dict` remembers its insertion order        | behave the same as cpython 3.8+                              | 1.0.9   |
| `~` and `@` operator                        | a.k.a. `__invert__` and `__matmul__`                         | 1.0.9   |
| platform identifier support                 | `print(sys.platform)`                                        | 1.0.9   |
| bytes literal                               | `b'\xff\x12'`                                                | 1.0.9   |
| load dynamic module                         | `__import__('libtest.so')`                                   | 1.0.9   |
| `colorsys` module                           | `import colorsys`                                            | 1.1.3   |
| `__all__` variable                          | `from xx import *` will read `__all__` if exists             | 1.1.3   |
| optional `box2d` module                     | see [box2d module](https://pocketpy.dev/modules/box2d/)      | 1.1.3   |
| line continuation character                 | `\` can be used for line continuation                        | 1.1.4   |
| `for..else` and `while..else`               | behave the same as cpython                                   | 1.1.6   |
| improved import system                      | relative/absolute import statements in directory and sub-directories | 1.1.7   |
| `typing` module                             | `from typing import List, Tuple, Any`                        | 1.1.8   |
| `datetime` module                           | get datetime of today and now                                | 1.1.8   |
| improved f-string support                   | most of the f-string usages in cpython are added             | 1.2.0   |
| `super()` shorthand support                 | `super().__init__(...)`                                      | 1.2.0   |
| improved type annotation                    | most type annotations up to python 3.11 are added            | 1.2.0   |
| 64-bit integers                             | `int` is always 64-bit, even in 32-bit platforms             | 1.2.1   |
| float accuracy improvement                  | with a new design, the accuracy of `float` was improved.     | 1.2.2   |
| goto/label feature (stable)                 | https://pocketpy.dev/features/goto/                          | 1.2.3   |
| improved `str.format`                 | `'{k}={v}'.format(k='a', v=1)`               | 1.2.4   |

## The Cheatsheet

You can check this [Cheatsheet](https://reference.pocketpy.dev/python.html) for a quick overview of the supported features between cpython and pocketpy.

### CODE REVIEW

**Comment by blueloveTH** [comment]
This pr can solve #2296. Because `v1.2.x` implements automatic float cast inside the api.

**Comment by blueloveTH** [comment]
https://github.com/nesbox/TIC-80/issues/2297

**Comment by blueloveTH** [comment]
All syntax errors were solved. The branch is able to pass all checks.

Now it is time to review semantic issues for each functions.

**Comment by blueloveTH** [comment]
```python
def trace(message, color=15): ...
def cls(color=0): ...
def btn(id: int): ...
def btnp(id: int, hold=-1, period=-1): ...
def circ(x: int, y: int, radius: int, color: int): ...
def circb(x: int, y: int, radius: int, color: int): ...
def elli(x: int, y: int, a: int, b: int, color: int): ...
def ellib(x: int, y: int, a: int, b: int, color: int): ...
def clip(x: int, y: int, width: int, height: int): ...
def exit(): ...
def fget(sprite_id: int, flag: int): ...
def fset(sprite_id: int, flag: int, b: bool): ...
def font(text: str, x: int, y: int, chromakey: int, char_width: int=8, char_height: int=8, fixed: bool=False, scale: int=1, alt: bool=False): ...
def key(code=-1): ...
def keyp(code=-1, hold=-1, period=-17): ...
def line(x0: int, y0: int, x1: int, y1: int, color: int): ...
def map(x: int=0, y: int=0, w: int=30, h: int=17, sx: int=0, sy: int=0, colorkey: int=-1, scale: int=1, remap: list=None): ...
def memcpy(dest: int, source: int, size: int): ...
def memset(dest: int, value: int, size: int): ...
def mget(x: int, y: int): ...
def mset(x: int, y: int, tile_id: int): ...
def mouse(): ...
def music(track=-1, frame=-1, row=-1, loop=True, sustain=False, tempo=-1, speed=-1): ...
def peek(addr: int, bits=8): ...
def peek1(addr: int): ...
def peek2(addr: int): ...
def peek4(addr: int): ...
def pix(x: int, y: int, color: int=None): ...
def pmem(index: int, value: int=None): ...
def poke(addr: int, value: int, bits=8): ...
def poke1(addr: int, value: int): ...
def poke2(addr: int, value: int): ...
def poke4(addr: int, value: int): ...
def print(text: str, x: int=0, y: int=0, color: int=15, fixed: bool=False, scale: int=1, smallfont: bool=False, alt: bool=False): ...
def rect(x: int, y: int, w: int, h: int, color: int): ...
def rectb(x: int, y: int, w: int, h: int, color: int): ...
def reset(): ...
def sfx(id: int, note: int=-1, duration: int=-1, channel: int=0, volume: int=15, speed: int=0): ...
def spr(id: int, x: int, y: int, colorkey: int=-1, scale: int=1, flip: int=0, rotate: int=0, w: int=1, h: int=1): ...
def sync(mask: int=0, bank: int=0, tocart: bool=False): ...
def time(): ...
def tstamp(): ...
def tri(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, color: int): ...  
def trib(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, color: int): ...
def ttri(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, u1: float, v1: float, u2: float, v2: float, u3: float, v3: float, texsrc: int=0, chromakey: int=-1, z1: float=0, z2: float=0, z3: float=0): ...
def vbank(bank: int=None): ...
```

**Comment by blueloveTH** [comment]
Done.

**Comment by TimotheeGreg** [comment]
Hi,
Thanks a lot for your work, that's great to have python on TIC-80!
I quickly mentioned pocketpy on the wiki with a link to the documentation https://github.com/nesbox/TIC-80/wiki/supported-languages#python-integration but I don't know much about it.
Feel free to modify or add anything useful there.

**Review by nesbox — APPROVED** [review]

**Pull request merged**
