### PR TITLE
Add Fennel as an option for creating games.

### LINKED ISSUE #594: Interest in Fennel support?
I have a patch where I've added support for the [Fennel programming language](https://fennel-lang.org) to TIC-80: https://github.com/technomancy/TIC-80/commit/d114930dbed917b8f79c6f71c20769cfff374cb8 (edit: note that the commit message shows a few steps which are still manual that need to happen if you want to try out that branch for yourself)

Fennel is a single-file compiler that emits Lua code, so as you can see it was not much work to get it supported; I followed the example from MoonScript which is similar, but MoonScript is a fair bit more complex overall.

If there is interest in having this in mainline TIC-80 I would be happy to polish up and submit it as a proper pull request. I'm one of the lead devs on the Fennel language, so if you have any questions about it I'm happy to answer them. If you decide it's not a good fit for mainline TIC-80 that's fine too; I can maintain the patches in my own fork and that's good enough for me.

### PR DESCRIPTION
**Pull request by technomancy**
This includes the original patch plus changes to the 3rd-party repo, as well adding a Fennel demo.

There is already a fair bit of duplication between Lua and Moonscript; this patch follows the example set by Moonscript, but this does introduce more duplication. If you like I can work on factoring out the common functions in a follow-up PR, in particular the repetition of `loadedlibs` in `luaapi.c`.

Fixes #594

### CODE REVIEW

**Comment by nesbox** [comment]
Thank you 👍

**Comment by nesbox** [comment]
Ahh, one more thing, please, don't forget to add yourself to the _Credits_ list here https://github.com/nesbox/TIC-80/wiki#credits

**Comment by technomancy** [comment]
Thanks; will do! I'll take a look at updating the documentation too. Is that all on the wiki, or is there anything in the main repo to update?

**Comment by nesbox** [comment]
only on the wiki so far

**Pull request merged**
