### PR TITLE
Arch latest flags

### LINKED ISSUE #367: Can't build on ArchLinux
```
$ make linux64
gcc `pkg-config --cflags gtk+-3.0` src/studio.c src/console.c src/run.c src/ext/file_dialog.c src/ext/md5.c src/ext/gif.c src/ext/net/SDLnet.c src/ext/net/SDLnetTCP.c src/ext/net/SDLnetselect.c src/fs.c src/tools.c src/start.c src/sprite.c src/map.c src/sfx.c src/music.c src/history.c src/world.c src/config.c src/keymap.c src/code.c src/dialog.c src/menu.c src/net.c src/surf.c src/tic80.c src/tic.c src/ext/blip_buf.c src/jsapi.c src/luaapi.c src/ext/duktape/duktape.c src/html.c -O3 -Wall -std=c99 -Iinclude/lua -Iinclude/zlib -Iinclude/gif -Iinclude/sdl2 -Iinclude/tic80 `pkg-config --libs gtk+-3.0` -Llib/linux -D_GNU_SOURCE -lSDL2 -llua -ldl -lm -lpthread -lrt -lz -lgif -flto -o bin/tic
lto1: fatal error: bytecode stream in file 'lib/linux/libSDL2.a' generated with LTO version 4.1 instead of the expected 6.0
compilation terminated.
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [makefile:276: linux64] Error 1
```
Tried with main trunk and 0.48.0.

I also tried by removing lib/linux/libSDL2..a. I have then the following error:
```
$ make linux64
gcc `pkg-config --cflags gtk+-3.0` src/studio.c src/console.c src/run.c src/ext/file_dialog.c src/ext/md5.c src/ext/gif.c src/ext/net/SDLnet.c src/ext/net/SDLnetTCP.c src/ext/net/SDLnetselect.c src/fs.c src/tools.c src/start.c src/sprite.c src/map.c src/sfx.c src/music.c src/history.c src/world.c src/config.c src/keymap.c src/code.c src/dialog.c src/menu.c src/net.c src/surf.c src/tic80.c src/tic.c src/ext/blip_buf.c src/jsapi.c src/luaapi.c src/ext/duktape/duktape.c src/html.c -O3 -Wall -std=c99 -Iinclude/lua -Iinclude/zlib -Iinclude/gif -Iinclude/sdl2 -Iinclude/tic80 `pkg-config --libs gtk+-3.0` -Llib/linux -D_GNU_SOURCE -lSDL2 -llua -ldl -lm -lpthread -lrt -lz -lgif -flto -o bin/tic
/usr/bin/ld: lib/linux/liblua.a(lapi.o): relocation R_X86_64_32 against hidden symbol `luaO_nilobject_' can not be used when making a shared object
/usr/bin/ld: lib/linux/liblua.a(ldebug.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(ldo.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(ldump.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lgc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lmem.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lobject.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lparser.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lstate.o): relocation R_X86_64_32S against hidden symbol `luaO_nilobject_' can not be used when making a shared object
/usr/bin/ld: lib/linux/liblua.a(lstring.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(ltable.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(ltm.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lundump.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lvm.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lauxlib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lbaselib.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lcorolib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(ldblib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lmathlib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lstrlib.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(ltablib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(loadlib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lptree.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lpcode.o): relocation R_X86_64_32S against symbol `numsiblings' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lcode.o): relocation R_X86_64_32S against hidden symbol `luaP_opmodes' can not be used when making a shared object
/usr/bin/ld: lib/linux/liblua.a(llex.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lpvm.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/liblua.a(lpcap.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/libz.a(deflate.o): relocation R_X86_64_32S against hidden symbol `_length_code' can not be used when making a shared object
/usr/bin/ld: lib/linux/libz.a(inflate.o): relocation R_X86_64_32S against hidden symbol `zcalloc' can not be used when making a shared object
/usr/bin/ld: lib/linux/libz.a(inftrees.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/libz.a(trees.o): relocation R_X86_64_32S against hidden symbol `_length_code' can not be used when making a shared object
/usr/bin/ld: lib/linux/libz.a(zutil.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/libz.a(compress.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/libz.a(uncompr.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/libz.a(crc32.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/libz.a(inffast.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/libgif.a(egif_lib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/linux/libgif.a(dgif_lib.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [makefile:276: linux64] Error 1
```

and then by removing all the .a, as I've all those libs installed, and archlinux recommand to build from sources as much as possible:

```
 rm lib/linux/lib*.a
```
```
$ make linux64
gcc `pkg-config --cflags gtk+-3.0` src/studio.c src/console.c src/run.c src/ext/file_dialog.c src/ext/md5.c src/ext/gif.c src/ext/net/SDLnet.c src/ext/net/SDLnetTCP.c src/ext/net/SDLnetselect.c src/fs.c src/tools.c src/start.c src/sprite.c src/map.c src/sfx.c src/music.c src/history.c src/world.c src/config.c src/keymap.c src/code.c src/dialog.c src/menu.c src/net.c src/surf.c src/tic80.c src/tic.c src/ext/blip_buf.c src/jsapi.c src/luaapi.c src/ext/duktape/duktape.c src/html.c -O3 -Wall -std=c99 -Iinclude/lua -Iinclude/zlib -Iinclude/gif -Iinclude/sdl2 -Iinclude/tic80 `pkg-config --libs gtk+-3.0` -Llib/linux -D_GNU_SOURCE -lSDL2 -llua -ldl -lm -lpthread -lrt -lz -lgif -flto -o bin/tic
/tmp/cc09wwjj.ltrans5.ltrans.o: In function `api_tick.lto_priv.864':
<artificial>:(.text+0x8d3d): undefined reference to `luaopen_lpeg'
collect2: error: ld returned 1 exit status
make: *** [makefile:276: linux64] Error 1
```

### PR DESCRIPTION
**Pull request by josefnpat**
First change relates to #367. Ubuntu won't compile if I remove the `-Llib/linux` from `LINUX64_LIBS`. I didn't make that change. 

Not entirely sure, but may fix #367 - can't tell until I test on my archbox.

Second change relates to makefile rename. Not sure if AUR maintainer needs to be informed.
Further reading for reason: https://www.gnu.org/software/make/manual/make.html#Makefile-Names

### CODE REVIEW

**Comment by nesbox** [comment]
Honestly, I don't understand what these changes do :(
I better will add instructions how to build TIC from scratch without prebuilt libs

**Comment by josefnpat** [comment]
@nesbox I made a typo. First change relates to #352.

Regardless, I don't really know what the flags do either. #352 wasn't really clear on what it did, and seens to be awol. I will say though that make takes a confusingly long time to compile. I'm wondering if all the files are being compiled in batch as opposed to letting make compile them in a dependency chain (thus compiling them in parallel.)

On a different note; can we rename `makefile` to `Makefile`?

**Comment by nesbox** [comment]
Long compile time is due `-flto` flag (Link Time Optimization) to reduce output size. I think we could have two versions with LTO and without it.
Ok, lets just rename `makefile->Makefile` in the PR (and I'll add How to Build from scratch instructions later)

**Comment by josefnpat** [comment]
@nesbox what if we added a flag that removes `-flto` then? That way we have smaller dev cycles, and the community will get the benefit of small binaries built from source.

**Comment by nesbox** [comment]
I created an issue #373
closing the PR then

**Pull request closed without merging**
