### PR TITLE
(chore) Migrate Raspberry Pi build instructions from wiki

### PR DESCRIPTION
**Pull request by joshgoebel**
I tried to simplify the instructions to make it better fit with the existing README build instruction style.

Original can still be found:

https://github.com/nesbox/TIC-80/wiki/Build-instructions

After this is merged I'll update the wiki fully.

### CODE REVIEW

**Review by nesbox — APPROVED** [review]
Thank you.

**Comment by badjano** [comment]
any chance we get a raspberry pi build on release?

**Comment by nesbox** [comment]
@badjano sure, also you can test dev build https://github.com/nesbox/TIC-80/actions?query=branch%3Amaster

**Comment by badjano** [comment]
WOW, didn´t know this was even possible... I feel like I don´t know github at all

**Comment by badjano** [comment]
I´m sorry, I can´t find the download link for rpi-baremetal

**Comment by nesbox** [comment]
You have to be signed in, scroll down and select artifact you want to download

**Comment by nesbox** [comment]
Screenshot_20210202-174558

**Comment by nesbox** [comment]
`tic80-baremetal` in your case

**Comment by badjano** [comment]
Thanks! I feel even more stupid now! LOL
Artifacts is a weird ass naming if you ask me, but ok! :) Thank you so much!

**Pull request merged**
