### PR TITLE
Fix counter and freq for libretro

### PR DESCRIPTION
**Pull request by jezze**
This is the follow up to my previous fix to make sure libretro works as well.

### CODE REVIEW

**Comment by jezze** [comment]
This have been validated to work on retroarch and fixes https://github.com/nesbox/TIC-80/issues/2065

**Review by joshgoebel — APPROVED** [review]
Looks about like what I'd expect.

**Comment by MineRobber9000** [comment]
Wouldn't this cause the same issues we were having earlier with `clock()` not being wall-time (see #1904)?

**Comment by joshgoebel** [comment]
Oh wait, yes what is `clock()` in libretro here?  If it's just the same old LIBc stuff then no, it won't work.  We need to be counting wall time.

**Review by nesbox — APPROVED** [review]

**Pull request merged**
