### PR TITLE
Add numpad keys to keycodes

### PR DESCRIPTION
**Pull request by cdwfs**
This PR is intended as a quick fix for #1452. It adds new entries to the `tic_keycode` enum for the keys on the numeric keypad, which were not previously recognized at all. The new keycodes are added to everywhere else I could find -- baremetalpi's `keycodes.h`, libretro's keymap, SDL's `keycodes.inl`, sokol, and the gamepad button list in `mainmenu.c`.

The primary motivation for this change is to make these keys available to the `key()` function and to allow gamepad buttons to be bound to them (to better support even more players from a single keyboard).

A non-goal of this PR is to fully support the numpad keys in the various editor modes. This would be a perfectly reasonable thing for users to expect, but would certainly involve some careful thought and interface decisions by the project owners.

### CODE REVIEW

**Comment by cdwfs** [comment]
Hello! First PR to TIC-80 here; if there's anything you'd like me to change, just let me know!

**Comment by cdwfs** [comment]
The Android build failure seems to be an unrelated infrastructure issue; from the logs:
```
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /opt/android-ndk/android-ndk-r21d/platforms/android-24/arch-x86_64/bin/dsymutil: no space left on device
Error: Docker pull failed with exit code 1
```
I see very similar errors in other open PRs #2244 and #2246

**Review by nesbox — APPROVED** [review]
looks good, thank you

**Comment by cdwfs** [comment]
Two follow-up questions:
1. I didn't update any of the documentation to reflect the new key map entries; should I push a follow-up PR with those changes?
2. I see there's a credits list; should I add myself, as a new contributor? :)

**Comment by nesbox** [comment]
Yes, pls, if not difficult
Pls update docs for `help` commands and in the wiki.
And pls update the credits list :)

**Pull request merged**
