### PR TITLE
Show how to build pro version

### PR DESCRIPTION
**Pull request by joshgoebel**
Is this supposed to be well hidden?  Why would someone building from source (possibly contributing to the project, etc) not want the pro version by default?  Could all the build instructions be updated to build pro or explain how?

This was not clear at all and took me like 10 minutes to figure out.

### CODE REVIEW

**Review by nesbox — APPROVED** [review]
Ok thank you, also we could add info how to build a release with `-DCMAKE_BUILD_TYPE=MinSizeRel` option. Because we are getting Debug build by default and it works quite slow.

**Comment by joshgoebel** [comment]
>  Because we are getting Debug build by default and it works quite slow.

How can I tell from the final build if it's a debug build or not?  I'm now following the steps in `build.yml` yet still I see `-dev` on my version... I would assume that building a production build should remove this?  

If -dev does not denote that could we add a if/else in `system.h` to add "Debug" to TIC_VERSION_LABEL?

**Comment by nesbox** [comment]
> How can I tell from the final build if it's a debug build or not? I'm now following the steps in `build.yml` yet still I see `-dev` on my version... I would assume that building a production build should remove this?

Yes, the prodution build is on `stable` branch with removed `dev` prefix.

> If -dev does not denote that could we add a if/else in `system.h` to add "Debug" to TIC_VERSION_LABEL?

I think it's  a good idea. Thanks.

**Comment by joshgoebel** [comment]
> could we add a if/else in system.h to add "Debug" to TIC_VERSION_LABEL?

I tried and failed to add this... I must now understand exactly what what a "debug" build means... neither DEBUG or EN_DEBUG seem to be set... i tried both.

**Pull request merged**
