### PR TITLE
Fix palette loading #902

### PR DESCRIPTION
**Pull request by kawa-yoiko**
From the semantics in `console.c`, it appears that the `palette` argument in `api_load()` denotes whether the palette should be loaded from the cart, i.e. if it is false, the palette will be overwritten with the one in the configuration.

https://github.com/nesbox/TIC-80/blob/634f3e7d7d78fdc0a0d7f3c2ccf2ce0f5356fa13/src/console.c#L377-L383

Also, I removed a redundant line of code. I have tested this with different combinations of cart loads, section loads and cart saves (both binary and text).

### CODE REVIEW

**Comment by nesbox** [comment]
As I see in the comments https://github.com/nesbox/TIC-80/issues/902#issuecomment-526449452 the PR doesn't fix the issue with a palette. Is it true? @kawa-yoiko

**Comment by kawa-yoiko** [comment]
We are unsure why RobLoach did not meet the problem at all, but I reproduced it and fixed it with this change (macOS with Clang). It would always be nice if more people could try this.

**Comment by StinkerB06** [comment]
Can he record a video of him trying to reproduce the bug?

**Comment by nesbox** [comment]
fixed here 15eb3a4
closing PR...

**Pull request closed without merging**
