### PR TITLE
add remap function

### PR DESCRIPTION
**Pull request by TheDrawingCoder-Gamer**
Changes:
- update wasm3 to latest commit
- changes the remap argument in wasm's map to a pointer holding a struct with data
- this data is used to call the remap function
- signature is the same so it's compatible

### CODE REVIEW

**Comment by TheDrawingCoder-Gamer** [comment]
can't figure out how to call WASM functions that return a value. if you can do that you could remove the res_ptr arg. the user_data arg could also possibly be removed if we made a holder struct that held a pointer and function pointer

**Review by nesbox — APPROVED** [review]

**Comment by nesbox** [comment]
@TheDrawingCoder-Gamer we have conflicts in the PR, could you pls resove?

**Comment by TheDrawingCoder-Gamer** [comment]
@nesbox done!

**Comment by TheDrawingCoder-Gamer** [comment]
@nesbox there is no longer a diff between pocketpy on this branch and main + it builds, so i think it's ready now

**Pull request merged**
