### PR TITLE
Poke1 and Peek1

### PR DESCRIPTION
**Pull request by SuperPupperDoggo**
I think these would be useful, especially for compact single-bit flags in save files.

### CODE REVIEW

**Comment by joshgoebel** [comment]
Though I wonder if the API should perhaps be different at that level... `bitset`, `bitget` or some such?

**Comment by StinkerB06** [comment]
This can already be done with existing `peek()` and `poke()`.

**Comment by SuperPupperDoggo** [comment]
that is a good point. poke1 and peek1 is more consistent considering that poke4 and peek4 exist, but it is also a bit weird. perhaps `pokebit` and `peekbit` would be a good name?

**Comment by joshgoebel** [comment]
> The same thing could be said for poke4 and peek4, and they still exist

I think it's about balancing the need for a useful API and how common certain operation are.  Since the graphics RAM is nibble based, peek4 and poke4 make a lot of sense for writing to VRAM.  That argument doesn't really hold up for peek1 and poke1, which are easy enough utilities to write by hand and wouldn't add the same amount of value to the same amount of people.

So it's not the same thing.

**Comment by SuperPupperDoggo** [comment]
> > The same thing could be said for poke4 and peek4, and they still exist
> 
> I think it's about balancing the need for a useful API and how common certain operation are. Since the graphics RAM is nibble based, peek4 and poke4 make a lot of sense for writing to VRAM. That argument doesn't really hold up for peek1 and poke1, which are easy enough utilities to write by hand and wouldn't add the same amount of value for the same amount of people.
> 
> So it's not the same thing.

I mean, you do have a point, but once again the same thing could be said for `poke4` and `peek4`. They are very rarely used. Writing directly to VRAM is not very common, because if you want to interact with individual pixels on the screen, `pix` is smaller in terms of size and more efficient than writing an algorithm to calculate the address of a pixel, and the palette is made up of 24-bit entries. While there is border color, most people don't even know it exists, and I have never seen it used.

**Comment by joshgoebel** [comment]
> While there is border color

Ah, yes, I forgot about nibble sized "registers" at various memory locations. :-)

**Comment by vsariola** [comment]
I'll just chime in that where I come (demoscene), we use poke4 / peek4 a lot to access video memory.

But regarding the design choice of packing nibbles in memory: I would've preferred not packing two nibbles in the video memory in the first place, but do it like c64 color memory: higher nibbles never used. Similarly, registers should not pack nibbles / bits if possible. This way, only poke and peek would be needed. TIC-80 ain't really using only 64k of memory, not even close, so  why bother making it more hard to do things.

**Review by nesbox — CHANGES_REQUESTED** [review]
Why not to add `peek2()/poke2()` in this case :)
Also, you can always call `peek(addr,1)` instead `peek1(addr)`, was added here #1475
Thanks

**Comment by joshgoebel** [comment]
I think the availability of both `poke(x, 1)` and `peek(x,1)` likely mean we should close this with "already exists"?

Should `peek4` and `poke4` possible be deprecated in a future release?  I assume they would have never been added if this more flexible `poke/peek` API had already existed at that time?

**Comment by vsariola** [comment]
Before deprecating them, let's a) profile the performance also, if the new poke api is slower to do the same thing or not. poke4/peek4 tends to be the hottest loops of them all: drawing fullscreen graphics for every pixel. b) consider if clean API is worth breaking existing cartridges, at least for a good while

**Comment by joshgoebel** [comment]
> Before deprecating them, let's a) profile the performance also, if the new poke api is slower to do the same thing or not. 

Ah, this is indeed a good suggestion and would perhaps be an argument for keeping.  It's quite possible that `poke4` and `peek4` are actually SLOWER though if they are just using the underlying more complex `poke` API anyways (or that the different really isn't significant).  I think that's what I recall from reading the source, but I could be mistaken.

> consider if clean API is worth breaking existing cartridges

_There are many ways to deprecate things_, there is no need to "break existing cartridges".  Rather it could simply be that when creating new cartridges those APIs are no long accessible, etc...

**Comment by nesbox** [comment]
I am against deprecating any API, it will break compatibility with old cartridges.
I'll merge this PR and going to add `poke2()/peek2()` since we have `peek4`

**Comment by nesbox** [comment]
Added peek2()/poke2() api here 2db3134

**Comment by joshgoebel** [comment]
Updating `peek` and `poke` API docs and consolidated the peek4/poke4 information there as well to avoid duplicating information everywhere.  I think we can explain everything better (and in more detail) in a single place.  I added redirects from the old API destinations (peek4/poke4).

- https://github.com/nesbox/TIC-80/wiki/peek
- https://github.com/nesbox/TIC-80/wiki/poke

The API docs do mention version 1.0 now, which is not released.... Should that we a link to a `versions` page where we explain which releases are out vs still in beta?  I think we need to keep the API up-to-date as we add things (even if they aren't yet released)... which means there will be mentions of 1.0.  I just wonder if that will lead to any confusion when someone gets looking for version 1 and can't find it?

**Comment by nesbox** [comment]
I usually add a badge with the version number in which this function works, like `(0.90)`

**Comment by joshgoebel** [comment]
Are you suggesting that instead of "added in 1.0"?

**Comment by nesbox** [comment]
Personally, I just like `(1.0)` 😄 but I don't mind

**Comment by joshgoebel** [comment]
Then I think I'll leave it for now, I like trying new things every once in a while - see how they feel. :)

**Pull request merged**
