### PR TITLE
bump janet version to 1.29.1

### PR DESCRIPTION
**Pull request by AlecTroemel**
closes https://github.com/nesbox/TIC-80/issues/2241

### CODE REVIEW

**Comment by AlecTroemel** [comment]
that android build failure looks like a docker pull timeout 

I havent been able to parse out why the windows XP builds is actually failing

**Comment by sogaiu** [comment]
Not sure how to parse things either, but isn't [the Android one](https://github.com/nesbox/TIC-80/actions/runs/5709564183/job/15468550368?pr=2244#step:2:146) something about running out of space?

For Windows XP, I noticed [this](https://github.com/nesbox/TIC-80/actions/runs/5709564183/job/15468552627?pr=2244#step:4:2027).  I think that might be referring to [this part](https://github.com/janet-lang/janet/blob/v1.29.1/src/core/util.c#L878) of Janet's source.

**Comment by AlecTroemel** [comment]
`profileapi.h` is a pretty recent addition https://github.com/janet-lang/janet/commit/e8e5f66f4cd2d5ae5fc2594662806a7f05407831. Though it appears like [that header has been around since windows 2000](https://learn.microsoft.com/en-us/windows/win32/api/profileapi/), so I'd think it would work with windows XP. My amateur cmake/make mind thinks there's probably some flag we need to include.. though thats a completely unfounded hunch. 

for the android docker thing, ya I just missread :disappointed:.. though to me running out of space is an odd error in a CI/CD pipeline. This [SO discussion](https://stackoverflow.com/questions/75536771/github-runner-out-of-disk-space-after-building-docker-image) seems possibly related.. though I dont really like any of the solutions :sweat_smile:

**Comment by AlecTroemel** [comment]
actually this blog suggests  profileapi.h **is not** present in windows XP wp.xin.at/archives/5484

wp.xin.at/archives/5484

**Comment by sogaiu** [comment]
> so JANET_GETTIME must not be defined, but the compiler sees it for an unknown reason

Puzzling.

---

I compared some of the output from `winxp` (failure):

```
-- The C compiler identification is MSVC 19.16.27050.0
-- The CXX compiler identification is MSVC 19.16.27050.0
...
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe - skipped
...
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe - skipped
```

to `windows` (success) output:

```
-- The C compiler identification is MSVC 19.29.30151.0
-- The CXX compiler identification is MSVC 19.29.30151.0
...
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
...
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
```

The compiler versions seem different.

Don't know if they are, and even if so, perhaps it makes no difference?

**Comment by sogaiu** [comment]
I looked into things a bit more.

Using info from [here](https://github.com/nesbox/TIC-80/blob/e7fbd51f3760b515c666cb45948aaecdbb846f21/.github/workflows/build.yml#L27-L28) and [here](https://learn.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-170), I setup things to replicate the build process locally for `winxp`.

Note that I changed:

```
cmake --build . --config %BUILD_TYPE% --parallel 
```

to:

```
cmake --build . --config MinSizeRel 
```

in the hopes that the output might be less confusing (not sure it made a difference).

I had some success in replicating the issue mentioned above about `profileapi.h`.

After the build stopped, I took a look at `vendor/janet/src/conf/janetconf.h`.  It looked unmodified from the clone of the upstream janet repository so I tried replacing it with [the file from @AlecTroemel's PR](https://github.com/AlecTroemel/TIC-80/blob/janet-1.29.1/build/janet/janetconf.h).

A subsequent execution of the `cmake --build . --config MinSizeRel` appears to have successfully built `tic80.exe`.

**Comment by sogaiu** [comment]
It's not pretty, but making the following changes and creating 1 file seems to work here.

First, the diff:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 72e00446..caf1ef92 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -476,6 +476,8 @@ message("BUILD_WITH_JANET: ${BUILD_WITH_JANET}")

 if(BUILD_WITH_JANET)

+    add_library(janet ${THIRDPARTY_DIR}/janet/build/c/janet.c)
+
     if(MINGW)
         find_program(GIT git)
         get_filename_component(GIT_DIR ${GIT} DIRECTORY)
@@ -491,6 +493,12 @@ if(BUILD_WITH_JANET)
             WORKING_DIRECTORY ${THIRDPARTY_DIR}/janet/
         )
     elseif(WIN32)
+        add_custom_command(TARGET janet
+            PRE_BUILD
+            COMMAND ./copy_janetconf_h.bat
+            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/build/janet
+        )
+
         add_custom_command(
             OUTPUT ${THIRDPARTY_DIR}/janet/build/c/janet.c
             COMMAND ./build_win.bat
@@ -504,7 +512,6 @@ if(BUILD_WITH_JANET)
         )
     endif()

-    add_library(janet ${THIRDPARTY_DIR}/janet/build/c/janet.c)
     target_include_directories(janet PUBLIC ${THIRDPARTY_DIR}/janet/src/include)
     target_include_directories(janet PUBLIC ${CMAKE_SOURCE_DIR}/build/janet/)
 endif()
```

Also, create `build/janet/copy_janetconf_h.bat` with content:

```
COPY /Y .\janetconf.h ..\..\vendor\janet\src\conf\janetconf.h
```

The basic idea is to copy `janetconf.h` into the source tree before the janet bootstrap binary is built -- but only for `WIN32`.

I tried a variety of ways to accomplish this but my cmake fu is virtually nonexistent and this seemed to work (^^;

**Comment by nesbox** [comment]
so, I update Janet module separately here cd05d0ab033e30e710de1cfefbc1375876ded605

**Comment by AlecTroemel** [comment]
Thank you @nesbox and @sogaiu for finishing this!.. I created this PR then had absolutely zero time to actually follow up on it :disappointed:

**Comment by sogaiu** [comment]
@nesbox and @AlecTroemel thanks for your efforts!

**Pull request closed without merging**
