### PR TITLE
D WebAssembly binding

### PR DESCRIPTION
**Pull request by PierceNg**

### CODE REVIEW

**Comment by joshgoebel** [comment]
Did you start with the template from WASM-4?

https://github.com/aduros/wasm4/tree/main/cli/assets/templates/d

I don't see any of the TIC-80 memory settings, etc... all the things specified in `dub.json` in the WASM-4 templates...

**Comment by PierceNg** [comment]
> Did you start with the template from WASM-4?
> 
> https://github.com/aduros/wasm4/tree/main/cli/assets/templates/d
> 
> I don't see any of the TIC-80 memory settings, etc... all the things specified in `dub.json` in the WASM-4 templates... we really don't want to re-invent the wheel but use the foundation they've already built over there for dealing with these things correctly.

Thanks for reviewing quickly. I actually didn't start from that. I'll look into it and put in what's missing.

**Review by nesbox — APPROVED** [review]
Awesome 👍

**Comment by joshgoebel** [comment]
@nesbox This wasn't really yet ready to merge.  Should I have immediately moved it to draft or assigned myself as a reviewer?

**Comment by nesbox** [comment]
Oops, sorry, I think we'll move it to draft next time to avoid misunderstandings.

**Pull request merged**
