### PR TITLE
Upgrade  janet to current master head

### PR DESCRIPTION
**Pull request by AlecTroemel**
includes a fix to windows builds, along with changes past version 1.36

### CODE REVIEW

**Comment by AlecTroemel** [comment]
Hmmm @Miguel-hrvs it looks like windows builds are still failing here :thinking:

**Comment by Miguel-hrvs** [comment]
@AlecTroemel Did you updated to master?

**Comment by AlecTroemel** [comment]
@Miguel-hrvs you mean for Janet? I did not, I checked out the commit tagged with the 1.36 release.

**Comment by Miguel-hrvs** [comment]
You can also enable again janet in mingw builds

**Review by nesbox — APPROVED** [review]

**Pull request merged**
