### PR TITLE
Proposal: remove support for `sokol`

### PR DESCRIPTION
**Pull request by aliceisjustplaying**
As far as I can tell this is not used anywhere anymore. It's not part of [the latest release](https://github.com/nesbox/TIC-80/releases/tag/v1.1.2837), doesn't get auto-built in the CI, and there aren't even instructions to build in the README either.

There may be use cases I'm not aware of, though.

If it's truly not in use, my proposal would be to simply remove it.

### CODE REVIEW

**Comment by nesbox** [comment]
Interesting, I had plans to use **Sokol** library as the default renderer for **win/linux/mac/wasm/android** and I started implementing it on this branch https://github.com/nesbox/TIC-80/tree/sokol

**Comment by nesbox** [comment]
We can remove Sokol support for now, but in the future, I'm going to bring it back by default

**Review by nesbox — APPROVED** [review]

**Comment by aliceisjustplaying** [comment]
Yeah I didn't see that one.

I stumbled into this bc based on my research it doesn't handle keyboard layout changes which I kind of needed for the AZERTY fix.

**Comment by aliceisjustplaying** [comment]
There are ways to do keyboard shortcuts that are keyboard-layout independent except here we do need that, for example.

**Pull request merged**
