### PR TITLE
Increase in possible notes for playing on piano roll, new keyboard layout (like in popular DAWs)

### PR DESCRIPTION
**Pull request by jejikeh**
Slightly changed the keyboard in the SFX editor so that it became more similar to the popular DAWs (Ableton, Garage Band, etc...)

1. Added the ability to switch between octaves on Z and X
2. Raised all the shortcuts one row higher (A, W, S, E, D, ...)
3. Increase the number of possible notes that can be played on the keyboard

### CODE REVIEW

**Comment by TimotheeGreg** [comment]
The same hotkeys apply on the tracker mode of the music editor. They should probably be consistent.

**Comment by jejikeh** [comment]
I added support for playing on the second octave in SFX piano roll as well as in Music Editor. Added shortcuts to change the octave.

1. To play on 1 octave press: Z../
2. To play on 2 octave press: Q..P
3. To change octave press: shift+z / shift+x

**Comment by TimotheeGreg** [comment]
I came across this today: #722 
That could be an issue to check before merging, or in the other way, your pull request could solve it.

**Comment by jejikeh** [comment]
Since in the SFC editor you can play notes by holding the keys. The note is played if you release ctrl before S. 

This can be fixed, but I'm afraid that the code will not be very good :\ (while it occurs to me to create a variable that will store the value of S while ctrl was pressed).

**Review by nesbox — APPROVED** [review]

**Pull request merged**
