### PR TITLE
flood fill paint function

### PR DESCRIPTION
**Pull request by anescient**
This is an implementation of Paul Heckbert's flood fill, providing the functionality of the QBasic PAINT method. This fills a contiguous area of solid color starting from a seed point.

All languages are supported, but not all languages are tested.

There's a closed/wishlist for this:  #2022

Edit: Actually this isn't quite like QB's PAINT. Continued below.

### CODE REVIEW

**Comment by anescient** [comment]
I was able to generate some torture tests that hit the stack limit around 3000, so I've changed the stack size to 4000. I'm not sure how to generate an absolute worst case, so I'm not sure how large is too large.

**Comment by sinsinpub** [comment]
just a random thought since qb mentioned, 2nd param bordercolor also frequently used and worth to be implemented?
image

**Comment by anescient** [comment]
> just a random thought since qb mentioned, 2nd param bordercolor also frequently used and worth to be implemented?

Definitely worth it but might need another implementation; I think this painter depends on stopping at its own color.

**Comment by anescient** [comment]
I went back to check the behavior of QB paint when it's given a border color, and it turns out there's _always_ a border color that just defaults to the paint color. For reference:

qbpaints1

I'm thinking tic paint should replicate this behavior if a border color is provided, but then unlike QB paint if no border color is given it should fill whatever contiguous space starts at the seed point, like I've implemented so far.

**Comment by anescient** [comment]
I'm finding QB paint is silly and shouldn't be replicated exactly. When a boundary color is given it's hard to predict whether the paint will leak through its own color:

qbpaints2

Rather than using QB as reference the behavior I'm going to pursue is: if a border color is given then paint to within the border color or the paint color itself, and as before, when no border color is given then effectively every color is border except the color at the seed point.

**Comment by anescient** [comment]
I found a worse worst case for memory usage which suggested the stack limit should be about 10,000 to be safe, so I've replaced the stack with a much smaller queue.

**Review by nesbox — APPROVED** [review]

**Pull request merged**
