### PR TITLE
New Pause() api function

### PR DESCRIPTION
**Pull request by sthilaid**
Hi! I wanted this functionality to ease debugging. This is not quite a breakpoint but is helpful nonetheless. What do you think? (I only implemented it in scheme for now to not waste time if this will be rejected).

### CODE REVIEW

**Comment by joshgoebel** [comment]
Feels like something you could easily build yourself outside the API just set aside a secondary controller for controlling things like pause, next frame, etc...

**Comment by nesbox** [comment]
I think you could do the same by calling 
```
trace('info')
exit()
```

**Comment by sthilaid** [comment]
@nesbox your suggestion is almost the same, BUT it seems that after `exit` is called, `resume` does not work (it doesn't restart the execution, or is it just me that is missing something?

**Comment by sthilaid** [comment]
@joshgoebel, how would you proceed to do this outside of the tic80 codebase? I'm not sure I understand your suggestion.

**Comment by joshgoebel** [comment]
> for controlling things like pause, next frame, etc...

Simply build these concepts into your program itself.  So it can pause, and then allow you to advance frame by frame. A simple state machine is all you need.

**Comment by nesbox** [comment]
Why if we modify the `exit()` api and make game able to resume after the call?

**Comment by BuoYancYdabl** [comment]
> Why if we modify the `exit()` api and make game able to resume after the call?

Most of the games that are logically quits after ending and user launches them again with resume: am I joke to you?

**Comment by sthilaid** [comment]
As @BuoYancYdabl mentioned, it seems like the exit method should keep it's semantic. 

@joshgoebel I see, indeed it would work, but it seems like a fair amount of overhead that each program needs to implement. It would be nice to be implemented at the API/core level. 

My implementation doesn't work very well, it was more a test and gather feedback and interest. It seems a lot of you are reluctant, so let's just forget about it :)

**Comment by joshgoebel** [comment]
> but it seems like a fair amount of overhead that each program needs to implement.

I really don't think it's that much effort, but perhaps I'm not thinking of something...

> It would be nice to be implemented at the API/core level.

I don't think we're going to add a full on debugger, so I honestly don't see the value for MOST users to be able to frame step without a full debugger.

**Pull request closed without merging**
